# Generated by Django 2.2.5 on 2019-09-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('judul', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=150, null=True)),
                ('authors', models.CharField(max_length=150, null=True)),
                ('source', models.CharField(max_length=150, null=True)),
                ('linksource', models.CharField(max_length=150, null=True)),
                ('detail', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
